import type { AppProps } from 'next/app';
import GlobalStyles from 'styles/globalStyles';
import Head from 'next/head';
import { Provider } from 'react-redux';
import { wrapper } from 'store/index';
import { ThemeProvider } from 'styled-components';
import theme from 'styles/theme';

function MyApp({ Component, ...rest }: AppProps) {
  const { store, props } = wrapper.useWrappedStore(rest);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ThemeProvider theme={theme}>
        <GlobalStyles />
        <Provider store={store}>
          <Component {...props.pageProps} />;
        </Provider>
      </ThemeProvider>
    </>
  );
}

export default MyApp;
