import type { NextPage } from 'next';
import Head from 'next/head';
import { useCallback, useState } from 'react';
import { useDispatch } from 'react-redux';
import { login, logout } from 'reducers/user';

const Home: NextPage = () => {
  const dispatch = useDispatch();

  const [id, setId] = useState('');
  const [password, setPassword] = useState('');

  const onChangeId = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const id = event.target.value;
      setId(id);
    },
    [],
  );

  const onChangePassword = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      const password = event.target.value;
      setPassword(password);
    },
    [],
  );

  const onSubmitForm = useCallback(
    (event: React.FormEvent) => {
      event.preventDefault();
      dispatch(login({ id, password }));
    },
    [id, password],
  );

  const onLogout = useCallback(() => {
    dispatch(logout());
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div
        style={{
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <form onSubmit={onSubmitForm}>
          <h1>로그인</h1>
          <br />

          <input type='text' onChange={onChangeId} />
          <br />
          <input type='text' onChange={onChangePassword} />
          <br />
          <div style={{ textAlign: 'center' }}>
            <button>로그인</button>
          </div>
        </form>
        <div>
          <button onClick={onLogout}>로그아웃</button>
        </div>
      </div>
    </div>
  );
};

export default Home;
