import AppLayout from 'components/appLayout';
import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';

interface Props {}

const Home: NextPage<Props> = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AppLayout>
        <div>post list</div>
      </AppLayout>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {},
  };
};

export default Home;
